inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - '*.gemspec'
    - 'Gemfile*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'

Metrics:
  Enabled: false

Style:
  Enabled: false

Layout:
  Enabled: false

Naming:
  Enabled: false
